# ==================================
# Database - PostgreSQL
# ==================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/travi_db - Dung neu chay tren local
#spring.datasource.url=jdbc:postgresql://postgres:5432/travi_db - Dung neu chay tren Docker, "postgres" la ten service trong docker-compose
spring.datasource.url=jdbc:postgresql://postgres:5432/travi_db
spring.datasource.username=postgres
spring.datasource.password=Lumitap2026
#spring.datasource.driver-class-name=org.postgresql.Driver



# ==================================
# JPA & Hibernate
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# ddl-auto: Tá»± Äá»ng cáº­p nháº­t cáº¥u trÃºc báº£ng trong DB dá»±a trÃªn cÃ¡c Entity (Class Java) cá»§a báº¡n mÃ  khÃ´ng lÃ m máº¥t dá»¯ liá»u cÅ©.
# dialect: Chá» Äá»nh ngÃ´n ngá»¯ SQL cá»¥ thá» cá»§a PostgreSQL Äá» Hibernate tá»i Æ°u hÃ³a cÃ¢u lá»nh.


# ==================================
# Redis
# ==================================
spring.data.redis.host=localhost
spring.data.redis.port=6379


# ==================================
# Spring AI - OpenAI
# ==================================
spring.ai.openai.api-key= ${OPENAI_API_KEY:sk-dummy-key-for-dev}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
#api-key: KhÃ³a API cá»§a OpenAI. CÃº phÃ¡p ${...:default} nghÄ©a lÃ : Æ¯u tiÃªn láº¥y tá»« biáº¿n mÃ´i trÆ°á»ng, náº¿u khÃ´ng cÃ³ thÃ¬ dÃ¹ng sk-dummy....
#temperature: Äá» "sÃ¡ng táº¡o" cá»§a AI (0.7 lÃ  má»©c cÃ¢n báº±ng giá»¯a logic vÃ  tá»± nhiÃªn).


# ===============================
# Swagger / Springdoc OpenAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.groups.enabled=true
# swagger-ui.path : ÄÆ°á»ng dáº«n Äá» xem tÃ i liá»u API (Giao diá»n trá»±c quan Äá» test API).


# ===============================
# Actuator (Monitoring)
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# exposure.clude Má» cÃ¡c cá»ng giÃ¡m sÃ¡t Äá» kiá»m tra sá»©c khá»e há» thá»ng


# ===============================
# Logging - Chi tiáº¿t Äá» debug
# ===============================
logging.level.root=INFO
logging.level.com.ota.travi=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level. Quy Äá»nh má»©c Äá» chi tiáº¿t cá»§a nháº­t kÃ½ há» thá»ng (INFO lÃ  bÃ¬nh thÆ°á»ng, DEBUG lÃ  ráº¥t chi tiáº¿t).

# ===============================
# DevTools
# ===============================
spring.devtools.restart.enabled=true