# =============================================
# TraVi-OTA - Application Profiles
# =============================================
spring.profiles.active=dev
spring.application.name=TraVi-OTA
server.port=8080