# =============================================
# TraVi-OTA - Application Profiles
# =============================================
spring.profiles.active=dev
spring.application.name=TraVi-OTA
server.port=8080

# =============================================
# JWT
# =============================================
SECRET_KEY=${JWT_SECRET_KEY}
JWT_EXPIRATION=${JWT_EXPIRATION_TIME}

# =============================================
# CORS Configuration
# =============================================
FRONTEND_URL=${FRONTEND_URL_ENV:http://localhost:5173}

